name: Rollout API-Gateway config

on:
  push:
    branches:
      - main
      
jobs:
  rollout-apigw-config:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Rollout API-GW config
    runs-on: ubuntu-latest
    steps:
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Rollout configuration
        run: |
          mkdir  $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          kubectl -n apim rollout restart deployment apim-traffic
          kubectl -n apim rollout restart deployment apim-apimgr
      - name: Verify Manager deployment
        run: kubectl -n apim rollout status deployment/apim-traffic
      - name: Verify Traffic deployment
        run: kubectl -n apim rollout status deployment/apim-traffic
